---
title: "DIIG Data Challenge - New Hire Visa Cases"
author: "Sara Mehta"
date: "Sunday, August 30, 2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
toc: yes
theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Section 1
### Data and packages
```{r, message = FALSE, warning = FALSE, echo = FALSE}
library(tidyverse)
library(usethis)

visa_cases <- read_csv("DIIG F20 Data Challenge #2.csv")

certified <- visa_cases %>% 
  filter(CASE_STATUS == "certified")
```


```{r filling-missing-values-for-variable}
certified <- certified %>%
  mutate(EDUCATION_LEVEL_REQUIRED = if_else(is.na(EDUCATION_LEVEL_REQUIRED),"No",EDUCATION_LEVEL_REQUIRED)) %>%
  mutate(COLLEGE_MAJOR_REQUIRED = if_else(is.na(COLLEGE_MAJOR_REQUIRED),"No",COLLEGE_MAJOR_REQUIRED)) %>%
  mutate(EXPERIENCE_REQUIRED_Y_N = if_else(is.na(EXPERIENCE_REQUIRED_Y_N),"n",EXPERIENCE_REQUIRED_Y_N)) %>%
  mutate(EXPERIENCE_REQUIRED_NUM_MONTHS = if_else(is.na(EXPERIENCE_REQUIRED_NUM_MONTHS),0,EXPERIENCE_REQUIRED_NUM_MONTHS)) %>%
  mutate(COUNTRY_OF_CITIZENSHIP = if_else(is.na(COUNTRY_OF_CITIZENSHIP),"NOT GIVEN",COUNTRY_OF_CITIZENSHIP))
```

```{r remove NAs}
new_certified <- na.omit(certified)
```


```{r creating full model}
lm_full <- lm(CASE_STATUS ~ EMPLOYER_NAME + EDUCATION_LEVEL_REQUIRED + COLLEGE_MAJOR_REQUIRED + EXPERIENCE_REQUIRED_Y_N + EXPERIENCE_REQUIRED_NUM_MONTHS + COUNTRY_OF_CITIZENSHIP + WORK_STATE_ABBREVIATION + VISA_CLASS + PAID_WAGE_PER_YEAR + JOB_TITLE_SUBGROUP, data = new_certified)

tidy(lm_full)
```

``` {r backward elimination}
lm_step <- lm_full %>%
step(direction = "backward", trace = 0)
lm_step
```



```{r 2-3-locations}
library(usmap)
library(ggplot2)

new_certified_v2 <- new_certified %>%
  rename(state = WORK_STATE)

plot_usmap(data = new_certified_v2, values = "state", color = "red") + 
  scale_fill_continuous(
    low = "white", high = "red", name = "Population (2015)", label = scales::comma
  ) + theme(legend.position = "right")
```




